version: '3'

services:
  db:
    image: postgis/postgis:13-3.0-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - "./pg:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  backend:
    build: ./backend/
    command:
      - /bin/sh
      - -c
      - |
        while ! nc -z db 5432; do sleep 1; done;
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}